version: '2'
services:
    socialapp-elasticsearch:
        image: elasticsearch:2.4.1
        restart: always
        volumes:
            - ~/volumes/jhipster/socialapp/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
