version: '2'
services:
    socialapp-postgresql:
        image: postgres:9.6.3
        restart: always
        volumes:
            - ~/volumes/jhipster/socialapp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=socialapp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
